
required = [
    "github.com/knative/serving/pkg/apis/serving",
    "github.com/concourse/atc",
    "k8s.io/client-go/kubernetes"
]

[[constraint]]
  name = "github.com/knative/serving"
  version = "v0.1.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.1"

# See:  https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "gopkg.in/fsnotify/fsnotify.v1"

